// Maps the "bezirk" (political district) values found in
// geodata/existing_turbines.geojson to their Bundesland — the turbine data
// itself has no bundesland property, only gemeinde/bezirk. Only districts
// that actually contain existing turbines are listed; extend when new
// districts show up in the data.
export const BEZIRK_TO_BUNDESLAND: Record<string, string> = {
	"Amstetten": "Niederösterreich",
	"Baden": "Niederösterreich",
	"Braunau": "Oberösterreich",
	"Bruck an der Leitha": "Niederösterreich",
	"Bruck-Mürzzuschlag": "Steiermark",
	"Deutschlandsberg": "Steiermark",
	"Eisenstadt-Umgebung": "Burgenland",
	"Freistadt": "Oberösterreich",
	"Gänserndorf": "Niederösterreich",
	"Hartberg-Fürstenfeld": "Steiermark",
	"Hermagor": "Kärnten",
	"Hollabrunn": "Niederösterreich",
	"Horn": "Niederösterreich",
	"Korneuburg": "Niederösterreich",
	"Krems": "Niederösterreich",
	"Leoben": "Steiermark",
	"Lilienfeld": "Niederösterreich",
	"Mattersburg": "Burgenland",
	"Melk": "Niederösterreich",
	"Mistelbach": "Niederösterreich",
	"Murtal": "Steiermark",
	"Mödling": "Niederösterreich",
	"Neusiedl": "Burgenland",
	"Neusiedl am See": "Burgenland",
	"Oberpullendorf": "Burgenland",
	"Ried im Innkreis": "Oberösterreich",
	"Scheibbs": "Niederösterreich",
	"Schärding": "Oberösterreich",
	"St. Pölten": "Niederösterreich",
	"St. Pölten Stadt": "Niederösterreich",
	"St. Pölten-Land": "Niederösterreich",
	"Steyr-Land": "Oberösterreich",
	"Urfahr-Umgebung": "Oberösterreich",
	"Voitsberg": "Steiermark",
	"Waidhofen an der Thaya": "Niederösterreich",
	"Weiz": "Steiermark",
	"Wien": "Wien",
	"Wiener Neustadt": "Niederösterreich",
	"Wolfsberg": "Kärnten",
	"Zwettl": "Niederösterreich",
};
